### ISSUE TITLE
Doesn't work on Windows, EntryPointNotFoundException

### ISSUE THREAD

**Issue by rasmus-z** [komietty/unity-vectorfield#16]
I get this error when I try to run it:
EntryPointNotFoundException: DecompAndSolveCholReal assembly:<unknown assembly> type:<unknown type> member:(null)
VectorField.Solver.Cholesky (MathNet.Numerics.LinearAlgebra.Double.SparseMatrix lhs, System.Double[] rhs) (at ./Packages/VectorField/Core/LinearAlgebra/Solver.cs:22)

**Comment by komietty** [comment]
I'm sorry for the trouble. I had pushed wip commits to the main branch which I shouldn't. Now I fixed .dll problem. You can try ;)
